version: "3.9"
services:
  app:
    container_name: flask-app
    hostname: web_api
    build: .
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: main
      FLASK_RUN_HOST: 0.0.0.0
      TEMPLATES_AUTO_RELOAD: 'True'
      FLASK_ENV: development
    ports:
      - '5000:5000'
    links:
      - database
    depends_on:
      - database
    volumes:
      - ./app:/app
    networks:
      - default
  database:
    image: mongo:7.0.2-jammy
    container_name: mongo
    hostname: mongo
    volumes:
      - ./mongo-volume:/data/db
      - ./mongo-volume/log:/var/log/mongodb/
    ports:
      - '27017:27017'
    networks:
      - default
volumes:
  persistent: